/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CompFecha;

/**
 *
 * @author Francisco A. Reyes
 */
public class CompruebaFecha extends javax.swing.JFrame {

    /**
     * Creates new form CompruebaFecha
     */
    public CompruebaFecha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoValido = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        campoDia = new javax.swing.JTextField();
        campoMes = new javax.swing.JTextField();
        campoAño = new javax.swing.JTextField();
        btnValido = new javax.swing.JButton();
        etiq1 = new javax.swing.JLabel();
        etiq2 = new javax.swing.JLabel();
        etiq3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoValido.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnValido.setText("Comprueba");
        btnValido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidoActionPerformed(evt);
            }
        });

        etiq1.setText("Día: ");

        etiq2.setText("Mes: ");

        etiq3.setText("Año:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiq1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(etiq2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiq3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoAño, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnValido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValido)
                    .addComponent(etiq1)
                    .addComponent(etiq2)
                    .addComponent(etiq3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoValido)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoValido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidoActionPerformed
        int valorDia = Integer.valueOf(campoDia.getText());
        int valorMes = Integer.valueOf(campoMes.getText());
        int valorAño = Integer.valueOf(campoAño.getText());
        boolean añoBisiesto = ((valorAño % 4) == 0 && ((valorAño % 100) != 0)) || ((valorAño % 400) == 0);
        /*Se puede crear una variable booleana que escriba el resultado campoValido.
        boolean resultado;
        Intercambiamos los "campoValido.setText("Fecha Correcta");" por la variable boolean resultado.
        Al final escribimos el resultado segun las variables
        En resumen, es lo mismo que este codigo pero cambiando los setText por variable resultado
        */
        if (valorDia > 0 && valorDia < 32) {
            if (valorMes > 0 && valorMes < 13) {
                if (valorMes != 2 && valorMes != 4 && valorMes != 6 && valorMes != 9 && valorMes != 11) {
                    campoValido.setText("Fecha Correcta");
                    
                } else {
                    switch (valorMes) {
                        case 2:
                            if (añoBisiesto == true) {
                                if (valorDia < 30 && valorDia > 0) {
                                    campoValido.setText("Fecha Correcta");
                                } else {
                                    campoValido.setText("Fecha Incorrecta");
                                }
                            } else {
                                if (valorDia < 29 && valorDia > 0) {
                                    campoValido.setText("Fecha Correcta");
                                } else {
                                    campoValido.setText("Fecha Incorrecta");
                                }
                            }
                            break;
                        case 4:
                            if (valorDia < 31 && valorDia > 0) {
                                campoValido.setText("Fecha Correcta");
                            } else {
                                campoValido.setText("Fecha Incorrecta");
                            }
                            break;
                        case 6:
                            if (valorDia < 31 && valorDia > 0) {
                                campoValido.setText("Fecha Correcta");
                            } else {
                                campoValido.setText("Fecha Incorrecta");
                            }
                            break;
                        case 9:
                            if (valorDia < 31 && valorDia > 0) {
                                campoValido.setText("Fecha Correcta");
                            } else {
                                campoValido.setText("Fecha Incorrecta");
                            }
                            break;
                        case 11:
                            if (valorDia < 31 && valorDia > 0) {
                                campoValido.setText("Fecha Correcta");
                            } else {
                                campoValido.setText("Fecha Incorrecta");
                            }
                            break;
                    }
                }
            } else {
                campoValido.setText("Fecha Incorrecta");
            } 
        } else {
            campoValido.setText("Fecha Incorrecta");
        }
    }//GEN-LAST:event_btnValidoActionPerformed
/* Otras formas de Codigo
    if (valorDia > 0 && valorDia < 32) {
            if (valorMes > 0 && valorMes < 13) {
                if (valorMes != 2 && valorMes != 4 && valorMes != 6 && valorMes != 9 && valorMes != 11) {
                    campoValido.setText("Fecha Correcta");
                    
                } else {
                    switch (valorMes) {
                        case 2:
                            if (añoBisiesto == true) {
                                if (valorDia < 30 && valorDia > 0) {
                                    campoValido.setText("Fecha Correcta");
                                } else {
                                    campoValido.setText("Fecha Incorrecta");
                                }
                            } else {
                                if (valorDia < 29 && valorDia > 0) {
                                    campoValido.setText("Fecha Correcta");
                                } else {
                                    campoValido.setText("Fecha Incorrecta");
                                }
                            }
                            break;
     CAMBIO AQUI        case 4:                            
                        case 6:
                        case 9:
                        case 11:
                            if (valorDia < 31 && valorDia > 0) {
                                campoValido.setText("Fecha Correcta");
                            } else {
                                campoValido.setText("Fecha Incorrecta");
                            }
                            break;
                    }
                }
            } else {
                campoValido.setText("Fecha Incorrecta");
            } 
        } else {
            campoValido.setText("Fecha Incorrecta");
        }
    }                           
    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompruebaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompruebaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompruebaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompruebaFecha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompruebaFecha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValido;
    private javax.swing.JTextField campoAño;
    private javax.swing.JTextField campoDia;
    private javax.swing.JTextField campoMes;
    private javax.swing.JTextField campoValido;
    private javax.swing.JLabel etiq1;
    private javax.swing.JLabel etiq2;
    private javax.swing.JLabel etiq3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
